const PRICE_NOTE = `Pricing is determined by the definition, location and scope of the work.`;

export default {
  code: 'en',
  htmlLang: 'en',
  ogLocale: 'en_GB',
  label: 'English',
  short: 'EN',
  priceNote: PRICE_NOTE,

  slugs: {
    regions: 'areas-we-cover',
    how: 'how-we-work',
    about: 'about-us',
    faq: 'faq',
    contact: 'contact',
    privacy: 'privacy-policy',
  },

  ui: {
    skip: `Skip to content`,
    menu: `Menu`,
    close: `Close`,
    langLabel: `Language`,
    home: `Home`,
    services: `Services`,
    regions: `Areas`,
    allServices: `All services`,
    allRegions: `Areas we cover`,
    inShort: `In short`,
    readMore: `Read more`,
    scope: `What is included`,
    approach: `How we work`,
    faqTitle: `Frequently asked questions`,
    relatedServices: `Related services`,
    serviceArea: `Fethiye and Seydikemer`,
    updated: `Updated`,
    breadcrumb: `Breadcrumb`,

    ctaQuote: `Get a free quote`,
    ctaQuoteShort: `Get a quote`,
    ctaWhatsapp: `WhatsApp`,
    ctaCall: `Call`,
    ctaPlan: `Home Care Plan`,
    tagNew: `New`,
    ctaMore: `Details`,

    formTitle: `Request a free quote`,
    formIntro: `Send us the form and we will get back to you within 2 hours during working hours. The quotation is free.`,
    fName: `Full name`,
    fPhone: `Phone / WhatsApp`,
    fEmail: `Email (optional)`,
    fService: `Which service?`,
    fRegion: `Location`,
    fMessage: `Briefly, what needs to be done?`,
    fTiming: `When would you like it done?`,
    fProperty: `Property type`,
    timing: { urgent: `Urgent (within days)`, week: `This week`, month: `Within this month`, later: `No rush — just getting a price` },
    property: { apartment: `Apartment`, villa: `Villa`, house: `Detached house`, business: `Business premises` },
    fServiceOther: `Which service? Briefly describe`,
    fAddress: `Address or location details (optional)`,
    fAddressOther: `Which area? Enter the address or neighbourhood`,
    fFiles: `Add photos or files (optional)`,
    fFilesHint: `Up to 5 files: photos or PDF. Photos are resized automatically.`,
    fFilesErr: `The files could not be attached. You can add up to 5 files (4 MB each; photos are resized automatically).`,
    fChoose: `Please select`,
    fOther: `Other`,
    fConsent: `I agree to my personal data being processed so that my request can be handled.`,
    fConsentLink: `Privacy policy`,
    fSubmit: `Send request`,
    callTitle: `We'll call you`,
    callIntro: `Leave your name and number and we will call you within 2 hours during working hours.`,
    callSubmit: `Call me back`,
    fSending: `Sending…`,
    fOk: `We have received your request. We will call you shortly.`,
    fErr: `The request could not be sent. Please message us on WhatsApp or call us.`,
    fRequired: `This field is required.`,
    fPhotoHint: `Adding photos speeds up the site visit. You can also send them on WhatsApp.`,

    trust: [
      `One point of contact: the company, not the tradesman`,
      `Written contract and workmanship guarantee`,
      `Photo report on every job`,
      `Türkçe · English · Русский`,
      `Free quotation`,
    ],

    footerAbout: `A service company delivering painting and renovation, pool maintenance, garden maintenance and plumbing across Fethiye and Seydikemer — with the company, not the tradesman, taking responsibility.`,
    footerContact: `Contact`,
    footerLegal: `Legal`,
    footerHours: `Working hours`,
    footerWeekdays: `Monday–Friday`,
    footerSaturday: `Saturday`,
    footerSunday: `Sunday`,
    footerClosed: `Closed`,
    rights: `All rights reserved.`,

    notFoundTitle: `Page not found`,
    notFoundText: `The page you are looking for may have been moved or removed.`,
    notFoundCta: `Back to home`,
  },

  home: {
    title: `Fethiye Painter, Renovation & Pool Care | Ustam Fethiye`,
    description: `Painting, renovation, pool and garden care and plumbing for villas and houses in Fethiye and Seydikemer. Written contract, workmanship guarantee, free quote.`,
    h1: `Stop chasing tradesmen. We take responsibility.`,
    lede: `Painting and renovation, pool, garden, plumbing and cleaning for villa and house owners across Fethiye and Seydikemer. One company, with a written contract, a workmanship guarantee and photo reports.`,

    promiseTitle: `Why Ustam Fethiye`,
    promiseLede: `Finding a tradesman in Fethiye is not the hard part. Knowing that he will turn up, that the price will hold and that the job will actually be finished — that is the hard part. This is exactly what we solve.`,
    promises: [
      { t: `One point of contact`, d: `What matters is not who does the work, but who stands behind it. If something goes wrong, you deal with the company.` },
      { t: `Written contract`, d: `Scope, timeline, materials and guarantee are defined in writing in a single document.` },
      { t: `Itemised quotation`, d: `Scope, materials and timeline in writing; the price stays fixed unless the scope changes.` },
      { t: `Workmanship guarantee`, d: `We stand behind the work we hand over. The guarantee terms are written into the contract.` },
      { t: `In your language`, d: `English, Russian and Turkish — including quotations and contracts.` },
      { t: `Photo report`, d: `If you are away from your property, you see the before, the progress and the result in photographs.` },
    ],

    compare: {
      title: `Hiring a tradesman or working with a company?`,
      lede: `Two routes: a tradesman you find yourself, or a company that answers for the result.`,
      colA: `A tradesman you find yourself`,
      colB: `Ustam Fethiye`,
      rows: [
        { k: `Who does the work?`, a: `A stranger; you check the references.`, b: `Our company's tradesmen; we plan and supervise.` },
        { k: `If something goes wrong`, a: `Your only contact is the tradesman.`, b: `Your contact is the company, the party to the contract.` },
        { k: `Price`, a: `Verbal; can drift mid-job.`, b: `Itemised in writing; fixed unless the scope changes.` },
        { k: `Contract and guarantee`, a: `Often a verbal agreement.`, b: `Written contract and workmanship guarantee.` },
        { k: `If you are away`, a: `You cannot see what is happening.`, b: `Written key handover; photo report at every stage.` },
        { k: `Communication`, a: `With the tradesman, sometimes several people.`, b: `One point of contact; Turkish, English, Russian.` },
      ],
    },
    pricing: {
      title: `Price depends on the job`,
      lede: `No two properties are alike. Instead of a price list, we understand the job and give you a clear written quotation.`,
      factors: [
        { t: `Location`, d: `Access, distance, estate or building rules, season.` },
        { t: `Size`, d: `Floor area, pool dimensions, garden area, number of floors.` },
        { t: `Scope of work`, d: `Scope, quality of materials, preparation and repair needs, timeline.` },
      ],
      stepsTitle: `How your quotation takes shape`,
      steps: [
        { t: `Short conversation`, d: `We listen by phone or WhatsApp.` },
        { t: `Photos or video`, d: `Even from abroad, we can see the job.` },
        { t: `Site visit`, d: `We measure if needed. Free.` },
        { t: `Written quotation`, d: `Itemised; fixed unless the scope changes.` },
      ],
    },

    servicesTitle: `Our services`,
    servicesLede: `Five core services, plus a care plan built for owners who manage their property from abroad.`,

    howTitle: `Four steps from survey to handover`,
    howLede: `Every job follows the same sequence. No surprises.`,

    regionsTitle: `Areas we cover`,
    regionsLede: `The whole of the Fethiye and Seydikemer districts. Each area has its own conditions — see the notes on each page.`,

    planTitle: `Your property is here. You are not.`,
    planLede: `The Home Care Plan is a monthly package for properties that stand empty most of the year: regular inspection visits, pool and garden maintenance, and a photo report every month.`,

    faqTitle: `Common questions`,
    ctaTitle: `Ask for a quote`,
    ctaLede: `Request a quote, message us on WhatsApp or call. We reply within 2 hours during working hours.`,
  },

  services: {
    painting: {
      slug: 'painting-and-renovation',
      name: `Painting & Renovation`,
      h1: `Painting & Renovation in Fethiye`,
      short: `Painting`,
      tagline: `Interior and exterior painting, plastering, bathroom and kitchen renovation.`,
      title: `Fethiye Painter & Renovation Contractor | Ustam Fethiye`,
      description: `Painter and renovation in Fethiye & Seydikemer: interior and exterior painting, bathrooms, kitchens. Written contract, workmanship guarantee, free quote.`,
      summary: [
        `We carry out interior painting, exterior painting and property renovation across Fethiye and Seydikemer.`,
        `The site visit is free; scope, timeline and materials are defined in a written quotation.`,
        `Every job starts with a written contract and is handed over with a workmanship guarantee.`,
        PRICE_NOTE,
      ],
      intro: [
        `The most common problem with painting and renovation work is scope creeping mid-job and the price moving with it. We settle that at the survey stage: we measure on site, photograph the condition of the surfaces and include the preparation work in the scope. The job we quote is the job we hand over.`,
        `In Fethiye the climate decides the outcome on exterior work. Sea humidity, salt and summer sun wear paint down quickly, and paint applied without proper surface preparation will fail within a season. That is why crack repair, priming and damp checks are separate line items in the quotation — not a surprise added later.`,
      ],
      scope: [
        `Interior painting (washable, satin, matt)`,
        `Exterior painting and facade refurbishment`,
        `Plastering, skim coat and surface levelling`,
        `Repair of cracks, damp and mould-damaged surfaces`,
        `Bathroom and kitchen renovation`,
        `Tiling`,
        `Plasterboard partitions and suspended ceilings`,
        `Painting of doors, windows and timber joinery`,
        `Coving and decorative detailing`,
      ],
      approach: [
        `Furniture, floors and joinery are covered and masked before work begins.`,
        `The paint brand and number of coats are stated in the contract.`,
        `The site is tidied every day and cleaned properly on completion.`,
        `We walk through a handover checklist with you at the end.`,
      ],
      faq: [
        { q: `Do you need a site visit before quoting for painting?`, a: `Yes. The condition of the surface matters as much as the square metres: cracks, damp or the type of existing paint all change the scope. Estimates given over the phone turn into disputes later, so we do not quote without seeing the property. The site visit is free.` },
        { q: `Do you supply the paint, or do we?`, a: `Either works. If we supply the materials, the brand and number of coats are written into the contract and the guarantee covers workmanship and application together. If you supply the materials, our workmanship guarantee still applies but material-related faults fall outside it.` },
        { q: `Can the work be done while the property is empty?`, a: `Yes, and it is the most practical arrangement when you are abroad. Keys are handed over and recorded in writing, and every stage of the work is photographed and sent to you.` },
        { q: `How long does the work take?`, a: `The duration is agreed at the survey and written into the contract. Painting a mid-sized apartment takes a few days; a full renovation can take several weeks. Start and handover dates are stated in the quotation.` },
        { q: `What is the best season for exterior painting?`, a: `Spring and autumn are the best windows. In midsummer high temperatures affect how the paint cures, and in winter humidity and rain affect adhesion. Interior work can be carried out all year round.` },
      ],
    },

    pool: {
      slug: 'pool-maintenance',
      name: `Pool Maintenance`,
      h1: `Pool Maintenance in Fethiye`,
      short: `Pool`,
      tagline: `Regular servicing, water balance, season opening and closing.`,
      title: `Pool Maintenance & Cleaning in Fethiye | Ustam Fethiye`,
      description: `Villa pool maintenance in Fethiye and Seydikemer: weekly service, water balance, filter checks, seasonal opening and closing. Photo reports, monthly plans.`,
      summary: [
        `We provide regular pool maintenance for villas and residential complexes across Fethiye and Seydikemer.`,
        `Visits are scheduled weekly, fortnightly or monthly; every visit is recorded.`,
        `Season opening, closing and winter care are included in the service.`,
        PRICE_NOTE,
      ],
      intro: [
        `Pool maintenance is a programme, not a one-off job. Water balance drifts within weeks, and a pool whose chemical values are not checked will inevitably turn green, scale up and wear out its equipment. That is why we set pool maintenance up as a monthly service agreement.`,
        `For owners who are not living at the property full time, the pool is the biggest worry. So that you know what condition it is in while you are away, we send a short note and photographs after every visit.`,
      ],
      scope: [
        `Surface and floor cleaning, vacuuming and brushing`,
        `Water testing (pH, chlorine, alkalinity) and chemical balancing`,
        `Filter cleaning and backwashing`,
        `Pump, motor and pipework checks`,
        `Emptying skimmer and pre-filter baskets`,
        `Season opening: water preparation and equipment start-up`,
        `Season closing and winter care`,
        `Minor repairs: seals, jets, lighting fittings`,
      ],
      approach: [
        `Readings and work carried out are recorded after every visit.`,
        `If chemical levels are running low, we tell you before topping up.`,
        `If we find an equipment fault: information first, then your approval, then the work.`,
        `Season opening is booked in advance during March and April.`,
      ],
      faq: [
        { q: `How often should a pool be serviced?`, a: `Weekly servicing is standard in summer and whenever the pool is in active use. If usage is heavy or the pool sits under trees, two visits a week may be needed. In winter, with the pool closed down, a fortnightly or monthly check is usually enough.` },
        { q: `Do you supply the chemicals?`, a: `Yes. Chemicals are supplied by us under the service agreement and the quantities used are recorded. If you prefer your own products to be used, that is noted in the agreement.` },
        { q: `Can you service the pool while I am abroad?`, a: `Yes — this is how we set it up for owners who live abroad. Access arrangements are recorded in writing and a short photo report is sent after every visit. This service can also be included in the Home Care Plan.` },
        { q: `My pool has turned green. Can you fix it?`, a: `Yes. A green pool is first put through a corrective shock treatment and then moved onto a regular maintenance programme. The corrective work, its duration and scope are assessed at the site visit separately from routine maintenance.` },
        { q: `What happens to the pool in winter?`, a: `The pool is closed down for winter: the water level is set, pipework is drained or frost-protected, winter chemicals are added and a cover is fitted. Periodic checks are recommended through the winter, as frozen or overflowing water can damage equipment.` },
      ],
    },

    garden: {
      slug: 'garden-maintenance',
      name: `Garden Maintenance`,
      h1: `Garden Maintenance in Fethiye`,
      short: `Garden`,
      tagline: `Lawns, pruning, irrigation systems and seasonal care.`,
      title: `Garden Maintenance in Fethiye & Seydikemer | Ustam Fethiye`,
      description: `Regular garden maintenance in Fethiye and Seydikemer: mowing, pruning, irrigation checks, tree care and seasonal planting.`,
      summary: [
        `We provide regular garden maintenance for villas and residential complexes across Fethiye and Seydikemer.`,
        `A visit schedule is set up; mowing, pruning, irrigation and clearing run under one arrangement.`,
        `Green waste is removed from the garden at the end of every visit.`,
        PRICE_NOTE,
      ],
      intro: [
        `In the Fethiye climate a garden needs attention all year. In summer everything depends on the irrigation system working; in winter, on pruning and feeding. Bringing a neglected garden back is always more expensive than maintaining it.`,
        `As with pools, we run garden work as a scheduled programme. How often we visit depends on the size of the garden, what is planted and how you use it — all agreed at the site visit.`,
      ],
      scope: [
        `Mowing, edging and lawn aeration`,
        `Pruning of shrubs, hedges and ornamental plants`,
        `Care of olive, citrus and palm trees`,
        `Drip and sprinkler irrigation checks and unblocking`,
        `Feeding and soil care`,
        `Weed clearance`,
        `Seasonal planting`,
        `Garden clearing and removal of green waste`,
      ],
      approach: [
        `The visit schedule is planned at the start of the season and confirmed with you.`,
        `Pruning is timed by species, not by the calendar.`,
        `The irrigation system is briefly checked on every visit.`,
        `Cuttings and green waste are never left in the garden.`,
      ],
      faq: [
        { q: `How often should the garden be maintained?`, a: `For gardens with lawn, weekly in summer and fortnightly in spring and autumn is typical. Gardens made up mainly of trees and shrubs may only need a monthly visit. The schedule is agreed together at the site visit.` },
        { q: `Do you repair irrigation faults as well?`, a: `Yes. Drip lines, sprinkler heads, filters and timer valves are covered under garden maintenance. Work on the mains supply or water tank side is planned together with our plumbing service.` },
        { q: `When do you prune?`, a: `It depends on the species. Olive and fruit trees are pruned at the end of winter; ornamentals and hedges are pruned periodically through the growing season. Pruning at the wrong time damages the plant, so the plant sets the calendar.` },
        { q: `Do you fell trees?`, a: `Under maintenance we prune and shape. Felling a large tree may require permission and different equipment, so we assess that separately at the site visit.` },
        { q: `Can the garden be maintained while I am away?`, a: `Yes. Garden maintenance suits owners who are away particularly well. A short photo report is sent after every visit, and the service can be folded into the Home Care Plan.` },
      ],
    },

    plumbing: {
      slug: 'plumbing',
      name: `Plumbing`,
      h1: `Plumber in Fethiye: Plumbing & Leak Detection`,
      short: `Plumbing`,
      tagline: `Leak detection, repairs, fittings and pipework renewal.`,
      title: `Fethiye Plumber: Plumbing & Leak Detection | Ustam Fethiye`,
      description: `Plumbing services in Fethiye and Seydikemer: leak detection and repair, drain unblocking, taps and fittings, water tanks and pressure pumps, pipework renewal.`,
      summary: [
        `We carry out plumbing repairs and pipework renewal across Fethiye and Seydikemer.`,
        `Leak detection, blocked drains, replacement of taps and fittings and full pipework renewal are covered.`,
        `Work is carried out under a written contract with a workmanship guarantee.`,
        PRICE_NOTE,
      ],
      intro: [
        `A water leak is the most expensive kind of damage a property can suffer — especially an unnoticed leak in an empty house, which takes the walls, the floor and the furniture with it. So on plumbing jobs we find the source first and plan the repair second.`,
        `Two situations come up constantly in Fethiye: frost and standing water in properties left empty over winter, and along the coast, hard water and scale shortening the life of fittings and pipework. Both are preventable with regular checks.`,
      ],
      scope: [
        `Leak detection and repair`,
        `Unblocking drains and waste pipes`,
        `Replacement of taps, fittings and shower systems`,
        `Installation of toilets, basins and baths`,
        `Water tank and pressure pump installation and servicing`,
        `Pipework renewal and system replacement`,
        `Filter and water treatment connections`,
        `Winter preparation: frost protection and draining down`,
        `Pre-season water reconnection and system check`,
      ],
      approach: [
        `Source first, repair second — we do not open up walls unnecessarily.`,
        `Where opening up is required, the scope and the making-good afterwards are written into the quotation.`,
        `Materials and brands used are recorded.`,
        `Pressure and flow are checked before handover.`,
      ],
      faq: [
        { q: `Can you find a leak without breaking into the walls?`, a: `We narrow the leak down first through visual inspection, meter monitoring and pressure testing, so that any opening up is kept to a minimum. We never break into a wall before the source is identified, and if opening up is needed we tell you the scope beforehand.` },
        { q: `How quickly can you attend an emergency?`, a: `We respond to enquiries within 2 hours during working hours. When we can attend on site depends on the location and that day's schedule, but active leaks are prioritised.` },
        { q: `My property is empty over winter. What should I do?`, a: `We recommend a winter preparation: closing the mains valve, draining down or frost-protecting the system, and a check before you return. This can be included in the Home Care Plan — it prevents the single most common form of damage in properties left empty.` },
        { q: `Do you supply the materials?`, a: `Usually yes, and everything used is listed in the quotation and handover document. We can equally fit taps or fittings you have chosen yourself — our workmanship guarantee still applies, with the product guarantee resting with the manufacturer.` },
        { q: `Will the property be unusable during pipework renewal?`, a: `It depends on the scope. For point repairs the water is off for a few hours. For a full renewal, the water interruption and the making-good period are agreed at the site visit and stated in the quotation in days.` },
      ],
    },

    cleaning: {
      slug: 'home-cleaning',
      name: `Home & Villa Cleaning`,
      short: `Cleaning`,
      h1: `Home & Villa Cleaning in Fethiye`,
      tagline: `Season opening and closing, guest changeovers, deep and post-renovation cleaning.`,
      title: `Fethiye Villa & Home Cleaning, Deep Cleaning | Ustam Fethiye`,
      description: `Villa and home cleaning in Fethiye and Seydikemer: season opening and closing, guest changeovers, deep and post-renovation cleaning. Written scope, free quote.`,
      summary: [
        `We provide cleaning for villas and detached houses across Fethiye and Seydikemer.`,
        `Season opening and closing, guest changeovers in holiday lets and post-renovation cleaning are covered.`,
        `The scope is set in a written checklist; owners who are away receive before-and-after photos.`,
        PRICE_NOTE,
      ],
      intro: [
        `Cleaning in villas and detached houses peaks at particular points in the year: clearing the dust and damp of the off-season when the season opens, preparing the house for winter when it closes, getting a holiday let ready between guests, and a fine clean after renovation or painting.`,
        `We run cleaning like our other services: as a job with a written scope. What will be cleaned, how many people and how long it takes, and how the handover is checked are agreed up front. For owners who are away, we photograph the before and after.`,
      ],
      scope: [
        `Deep cleaning of interiors (floors, surfaces, behind and around furniture)`,
        `Detailed kitchen and bathroom cleaning`,
        `Windows, frames and glazing`,
        `Season-opening clean: dusting, airing, beds and linen preparation`,
        `Season-closing clean and protection for the off-season`,
        `Guest changeover cleaning and preparation for holiday lets`,
        `Fine cleaning after renovation, painting or building work`,
        `Terrace, balcony and outdoor area sweeping and washing`,
      ],
      approach: [
        `The scope and areas are set in a written checklist before the work starts.`,
        `Access is arranged with a signed key handover; valuables and locked areas are agreed in advance.`,
        `At the end the job is handed over against the checklist; if you are away, the before and after are photographed.`,
        `Products are chosen to suit sensitive surfaces such as natural stone and timber.`,
      ],
      faq: [
        { q: `Do you need a site visit for cleaning?`, a: `For small and standard jobs, a short conversation and photos can be enough to settle the scope. For large villas or post-renovation work we need to see the property.` },
        { q: `Can you clean my holiday let between guests?`, a: `Yes. Cleaning is planned around your check-in and check-out calendar, and the house is prepared for the next guests.` },
        { q: `Who supplies the cleaning products?`, a: `Usually the crew brings its own; the products used are stated in the agreement. If you prefer your own products, they can be used.` },
        { q: `Can the cleaning be done while the house is empty?`, a: `Yes. The key is taken over against a written record and a photo report is sent once the job is done.` },
        { q: `Do you offer regular cleaning?`, a: `Yes, as a one-off job or a regular programme. For owners who are away, cleaning can be included in the Home Care Plan.` },
      ],
    },

    homecare: {
      slug: 'home-care-plan',
      name: `Home Care Plan`,
      h1: `Villa & Home Care Plan in Fethiye`,
      short: `Home Care Plan`,
      tagline: `Monthly inspection and maintenance for owners who are away.`,
      title: `Fethiye Villa Care & Home Care Plan | Ustam Fethiye`,
      description: `Monthly care plan for villas and homes left empty in Fethiye and Seydikemer: regular checks, pool and garden care, photo reports, seasonal preparation.`,
      featured: true,
      summary: [
        `The Home Care Plan is a monthly package for properties that stand empty for most of the year.`,
        `It covers regular inspection visits, photo reports, pool and garden maintenance, and season opening and closing.`,
        `Plan holders are prioritised for plumbing and renovation requests.`,
        PRICE_NOTE,
      ],
      intro: [
        `Many properties across Fethiye and Seydikemer are used for only a few months a year. In a house whose owner is abroad, a small leak goes unnoticed for months, the garden gets away from you, the pool deteriorates — and the bill lands at the start of the season.`,
        `The Home Care Plan exists to prevent exactly that. We visit the property on a schedule, work through a checklist and send you a photo report after every visit. While you are away, you see the state of your property every month.`,
      ],
      scope: [
        `Monthly inspection visit against a fixed checklist`,
        `Monthly photo report on the condition of the property`,
        `Checks for leaks, damp and humidity`,
        `Pool maintenance (depending on the package)`,
        `Garden maintenance (depending on the package)`,
        `Pre-season opening: airing, cleaning, water and plumbing checks`,
        `End-of-season closing: winter preparation and frost protection`,
        `Preparation checks before guests or tenants arrive`,
        `First response and notification when a problem is found`,
      ],
      approach: [
        `A fixed checklist is drawn up for each property and every visit follows it.`,
        `Where keys are held, handover and return are recorded in writing.`,
        `If we find a problem, we inform you first — nothing starts without your approval.`,
        `Work outside the plan is quoted separately, with plan holders given priority.`,
      ],
      faq: [
        { q: `Who is the Home Care Plan for?`, a: `It is designed for owners of property in Fethiye or Seydikemer who live in another city or country for most of the year, for owners of villas let out to guests, and for families who use their property seasonally.` },
        { q: `Do I have to give you keys?`, a: `No. Outdoor services such as garden and pool maintenance can be carried out without keys. Keys are only needed for interior checks, and both handover and return are recorded in writing.` },
        { q: `How does the report arrive?`, a: `After every visit we send dated photographs and a short note by WhatsApp or email. If we have found a problem, you get photographs, an explanation and our recommendation.` },
        { q: `What happens if something outside the plan comes up?`, a: `We tell you first. If you approve, the work is carried out under a separate quotation and contract. Plan holders are given priority in scheduling.` },
        { q: `Is the plan a fixed commitment?`, a: `The programme runs monthly, and both the visit frequency and the scope are agreed together at the site visit. The details are then set out in writing in the agreement.` },
      ],
    },
  },

  regions: {
    title: `Areas We Cover — Fethiye & Seydikemer | Ustam Fethiye`,
    description: `Painting, renovation, pool, garden and plumbing services in Fethiye centre, Calis, Oludeniz, Ovacik, Hisaronu, Kayakoy, Gocek, Uzumlu and Seydikemer.`,
    h1: `Areas we cover`,
    lede: `We cover the whole of the Fethiye and Seydikemer districts. Each area has its own conditions — below is what typically comes up in each of them.`,
    inRegion: `Our services in this area`,
    regionNotes: `Local notes`,
    items: {
      'merkez': { slug: 'fethiye-centre', name: `Fethiye Centre`,
        intro: `Central Fethiye is dominated by apartments, gated developments and commercial premises. The most common needs are interior painting and renovation, bathroom and kitchen refurbishment, and plumbing repairs.`,
        notes: [
          `Apartment blocks and complexes have working-hour and noise rules; we plan the schedule around the management's requirements.`,
          `In older central buildings the age of the pipework is a frequent source of trouble — renewing a run is often more economical than repeated point repairs.`,
          `In buildings without a lift, carrying materials affects the duration, and we account for that at the survey.`,
        ], services: ['painting', 'plumbing', 'homecare'] },
      'calis': { slug: 'calis', name: `Calis`,
        intro: `Close to the seafront at Calis, salt-laden humidity and wind set the agenda. Exterior painting, joinery care and scale in the plumbing are what come up most here.`,
        notes: [
          `On seafront elevations salt and humidity wear paint down far faster; surface preparation and the right primer are critical.`,
          `Metal railings, joinery and outdoor fittings need regular corrosion checks.`,
          `Winter wind and rain mean exterior work has to be planned around the season.`,
        ], services: ['painting', 'garden', 'homecare'] },
      'oludeniz': { slug: 'oludeniz', name: `Oludeniz`,
        intro: `Oludeniz has a high concentration of villas with pools and properties let to guests. Heavily used pools and constant guest turnover both demand regular maintenance.`,
        notes: [
          `In rental villas pool usage is heavy, so a single weekly visit is often not enough; the schedule is built accordingly.`,
          `Quick checks and small repairs are frequently needed around guest changeover dates, so we plan those into the calendar in advance.`,
          `Demand for pre-season pool and plumbing checks peaks in March and April — book early.`,
        ], services: ['pool', 'cleaning', 'homecare'] },
      'ovacik-hisaronu': { slug: 'ovacik-hisaronu', name: `Ovacik & Hisaronu`,
        intro: `Ovacik and Hisaronu have a high proportion of overseas owners, and much of the housing stock stands empty for most of the year. Regular maintenance that can be followed remotely is what is needed most here.`,
        notes: [
          `In properties closed up for long periods, damp and standing-water plumbing problems are among the most common problems.`,
          `Many owners here live abroad; we handle communication in English or Russian and send a photo report after every visit.`,
          `In gated developments, communal rules and management permissions affect the schedule — we sort that out in advance.`,
        ], services: ['homecare', 'plumbing', 'pool'] },
      'kayakoy': { slug: 'kayakoy', name: `Kayakoy`,
        intro: `Kayakoy and the surrounding area is dominated by stone-built and older properties, where painting and repair work needs a different approach from standard housing.`,
        notes: [
          `On stone and old render, breathable products matter; the wrong coating traps moisture inside the wall.`,
          `Where damp and mould have damaged surfaces, the source of the moisture has to be resolved before any painting.`,
          `Garden and olive grove maintenance is frequently requested here, with pruning timed by tree.`,
        ], services: ['painting', 'garden', 'homecare'] },
      'gocek': { slug: 'gocek', name: `Gocek`,
        intro: `In Gocek, villa and development standards are high and the expectation is continuous, scheduled maintenance. Pool, garden and property care are mostly run under agreement.`,
        notes: [
          `Development managers and villa owners expect a fixed programme and reporting; every visit is recorded.`,
          `The property is expected to stay guest-ready through the season, so inspection visits are scheduled more frequently.`,
          `Given the distance from the centre, we plan visits efficiently and keep unscheduled trips to a minimum.`,
        ], services: ['pool', 'garden', 'homecare'] },
      'uzumlu': { slug: 'uzumlu', name: `Uzumlu`,
        intro: `Uzumlu sits above the coast and its winters are noticeably colder. Winter preparation and frost protection are therefore the standout jobs here.`,
        notes: [
          `Frozen pipework is a real risk in properties left empty over winter; we recommend draining down and frost protection at season close.`,
          `The difference in altitude shifts the garden calendar compared with the coast, so pruning and planting are timed differently.`,
          `The spring and autumn window for exterior work is narrower than on the coast, so we plan early.`,
        ], services: ['plumbing', 'garden', 'painting'] },
      'seydikemer': { slug: 'seydikemer', name: `Seydikemer`,
        intro: `Seydikemer is a large, rural district of detached houses, properties with land and farmland. Garden maintenance, plumbing and water tank or pressure pump work are the most frequent needs.`,
        notes: [
          `Distances are long, so we group visits and build travel into the schedule.`,
          `Where mains pressure is inconsistent, a water tank and pressure pump is the usual solution.`,
          `On large plots a regular maintenance programme always works out cheaper than a one-off clearance.`,
        ], services: ['garden', 'plumbing', 'painting'] },
    },
  },

  pages: {
    how: {
      title: `How We Work — From Enquiry to Handover | Ustam Fethiye`,
      description: `The Ustam Fethiye process: enquiry, free site visit, written quotation, contract, scheduling, delivery, handover and guarantee. Every job follows the same eight steps.`,
      h1: `How we work`,
      lede: `Every job follows the same eight steps. The aim is simple: you know what will be done, how long it will take and what it will cost — in writing, before anything starts.`,
      steps: [
        { t: `Enquiry`, d: `You reach us by form, WhatsApp or phone. Every enquiry is logged, and we reply within 2 hours during working hours.` },
        { t: `First conversation`, d: `A short call to establish the scope, the location and how urgent it is. Photographs, if you have them, speed this up.` },
        { t: `Free site visit`, d: `We measure, photograph and take notes on site. Site visits are free across Fethiye and Seydikemer.` },
        { t: `Written quotation`, d: `Scope line by line, the timeline and the materials, all in writing. The quotation carries a validity period.` },
        { t: `Contract`, d: `Scope, start and handover dates, materials and guarantee in a single document. The contract is also provided in your language.` },
        { t: `Scheduling`, d: `The team is assigned, materials are procured and you are given a start date.` },
        { t: `Delivery and supervision`, d: `We supervise on site, record progress in photographs and keep you informed.` },
        { t: `Handover and guarantee`, d: `We walk through the checklist with you and hand over the job file and guarantee document. A follow-up call comes afterwards.` },
      ],
      stepsTitle: `Eight steps`,
      guaranteeTitle: `Our commitments`,
      guarantees: [
        { t: `You deal with the company`, d: `The team carrying out the work is our supplier. The party under contract with you and responsible for the job is Ustam Fethiye.` },
        { t: `The price holds unless the scope changes`, d: `Once the quotation is accepted, the price is fixed unless you ask for something different or something appears that could not be seen at the survey. In that case: information first, then your approval, then the work.` },
        { t: `Workmanship guarantee`, d: `We stand behind the work we hand over. The guarantee period and its scope depend on the service and are written into the contract.` },
        { t: `Site discipline`, d: `The working area is tidied every day, cleaned properly on completion and all waste removed.` },
      ],
    },

    about: {
      title: `About Us — Ustam Fethiye`,
      description: `Ustam Fethiye is a service company delivering painting and renovation, pool maintenance, garden maintenance and plumbing across Fethiye and Seydikemer, with the company taking responsibility for the work.`,
      h1: `About us`,
      lede: `Ustam Fethiye was set up to solve the problem of finding a good tradesman — not as an introduction service, but as a company that takes responsibility for the result.`,
      body: [
        { t: `What we do`, p: [
          `We deliver painting and renovation, pool maintenance, garden maintenance and plumbing across Fethiye and Seydikemer. We carry out the site visit, prepare the quotation, sign the contract, schedule the work, supervise it and hand it over.`,
          `The tradesmen and teams who carry out the work on site are our suppliers. The party under contract with you, and responsible for the outcome, is the company. That is our fundamental difference.`,
        ]},
        { t: `Why this company was needed`, p: [
          `Finding a tradesman in Fethiye is not difficult. What is difficult is being certain he will turn up on the day he promised, that the price will not move mid-job, and that the work will be finished — and having someone to call when it is not.`,
          `For owners whose property is in Fethiye while they live in another country, language and distance are added on top. Not being able to see what is happening at the property is the most common worry, and it is why we send a photo report on every job.`,
        ]},
        { t: `How we work`, p: [
          `Every job begins with a written quotation and contract. Scope, timeline, materials and guarantee are set out in writing before anything starts. Site visits are free, and we do not quote without one — estimates given over the phone are the single biggest cause of disputes in this trade.`,
          `Communication runs through one channel. You do not deal with the team on site; we do. Your point of contact is always the same person.`,
        ]},
        { t: `Languages`, p: [
          `We work in English, Russian and Turkish. All correspondence, including quotations and contracts, can be handled in the language you prefer.`,
        ]},
      ],
      factsTitle: `At a glance`,
      facts: [
        { k: `Service area`, v: `Fethiye and Seydikemer districts` },
        { k: `Services`, v: `Painting and renovation, pool maintenance, garden maintenance, plumbing, Home Care Plan` },
        { k: `Languages`, v: `Turkish, English, Russian` },
        { k: `Site visit`, v: `Free within the service area` },
        { k: `Pricing`, v: PRICE_NOTE },
        { k: `Contract`, v: `Every job is carried out under a written contract` },
        { k: `Guarantee`, v: `Workmanship guarantee, scope stated in the contract` },
        { k: `Response time`, v: `Within 2 hours during working hours` },
      ],
    },

    faq: {
      title: `Frequently Asked Questions | Ustam Fethiye`,
      description: `Common questions about Ustam Fethiye: site visits, pricing, contracts, guarantees, service area, languages and remote property care.`,
      h1: `Frequently asked questions`,
      lede: `If your question is not answered here, message us — we reply the same day.`,
      items: [
        { q: `Which areas do you cover?`, a: `We cover the whole of the Fethiye and Seydikemer districts, including Fethiye centre, Calis, Karagozler, Oludeniz, Ovacik, Hisaronu, Kayakoy, Gocek, Uzumlu and the surrounding area.` },
        { q: `Do you charge for the site visit?`, a: `No. Site visits are free within our Fethiye and Seydikemer service area. We measure, photograph and then prepare your written quotation.` },
        { q: `How do you set your prices?`, a: `Pricing is determined by the definition, location and size of the work. We start with a short conversation and, if needed, photos or video; when necessary we carry out a free site visit. We then prepare an itemised written quotation, and the price holds unless the scope changes.` },
        { q: `Can you give me a rough price over the phone?`, a: `In an initial conversation we can give you a rough frame for the size of the job from photos or video. But because no two properties are alike, a binding price is given in a written quotation once we have understood the job properly and, where needed, carried out a free site visit. Firm numbers given without seeing the property tend to change mid-job, which is the single biggest cause of disputes in this trade.` },
        { q: `Who actually does the work?`, a: `The work is carried out by the tradesmen and teams we work with. But the party under contract with you — planning, supervising and answerable for the result — is the company. You do not deal with the team on site; we do.` },
        { q: `Do you work under contract?`, a: `Yes, every job is carried out under a written contract covering scope, start and handover dates, materials, payment terms and guarantee. The contract is also provided in your preferred language.` },
        { q: `Do you give a guarantee?`, a: `Yes. We provide a workmanship guarantee on the work we hand over; the period and scope vary by service and are set out in the contract. Where we supply the materials, the product guarantee is handled alongside it.` },
        { q: `I live abroad. How will you look after my property?`, a: `Many property owners in the area live overseas. We handle communication in English or Russian, record any key handover in writing, and send a photo report at every visit or stage of work. For ongoing care we offer the Home Care Plan.` },
        { q: `What languages do you work in?`, a: `Turkish, English and Russian. All correspondence, including quotations and contracts, can be handled in the language you prefer.` },
        { q: `How quickly do you respond?`, a: `Within 2 hours for enquiries received during working hours. Enquiries received outside those hours are dealt with first thing on the next working day.` },
        { q: `Who supplies the materials?`, a: `Usually we do, and the brands and products used are listed in the quotation. You are also welcome to supply materials yourself; our workmanship guarantee still applies, but material-related faults fall outside it.` },
        { q: `Do you work with development or building managements?`, a: `Yes. We carry out periodic maintenance and seasonal refurbishment for residential developments, apartment managements, villa rental companies and small hotels or guesthouses. We arrange a separate meeting for work of that kind.` },
      ],
    },

    contact: {
      title: `Contact & Free Site Visit | Ustam Fethiye`,
      description: `Request a free site visit in Fethiye and Seydikemer. Reach us by form, WhatsApp or phone — we reply within 2 hours during working hours.`,
      h1: `Contact`,
      lede: `Site visits are free. Fill in the form, message us on WhatsApp or simply call — we reply within 2 hours during working hours.`,
      infoTitle: `Reach us directly`,
      areaTitle: `Service area`,
      areaText: `The whole of the Fethiye and Seydikemer districts: the centre, Calis, Karagozler, Oludeniz, Ovacik, Hisaronu, Kayakoy, Gocek, Uzumlu and the surrounding area.`,
    },

    privacy: {
      title: `Privacy Policy | Ustam Fethiye`,
      description: `How Ustam Fethiye processes, stores and protects your personal data, and what your rights are.`,
      h1: `Privacy and data protection`,
      lede: `This page explains how the personal data you share with us through the contact form and other channels is handled.`,
      sections: [
        { t: `What we collect`, p: [`Through the contact form we collect your name, phone number, optionally your email address, the service you are asking about, your location and whatever you tell us in your message. We also record the page the enquiry came from and the date.`] },
        { t: `Why we collect it`, p: [`Your data is processed solely to assess your enquiry, contact you, arrange a site visit, prepare a quotation and contract, and deliver the service. We do not send marketing communications without your consent.`] },
        { t: `Who we share it with`, p: [`We do not sell your data or share it for marketing purposes. Only the minimum information needed to carry out the work — such as the address and the job description — is shared with the relevant team. Disclosure to authorities may occur where legally required.`] },
        { t: `How long we keep it`, p: [`Enquiries that do not proceed are deleted after a reasonable period. Where a contract is entered into, records are retained for the periods required by law.`] },
        { t: `Your rights`, p: [`Under Turkish data protection law (KVKK, Law No. 6698) you have the right to access your data and to request its correction, deletion or restriction. If you are resident in the European Union or the United Kingdom, your rights under the GDPR also apply. Please send any request to the contact address below.`] },
        { t: `Cookies and analytics`, p: [`This site does not use advertising or tracking cookies. Visit statistics are collected using a cookie-free method that does not gather personal data.`] },
      ],
    },
  },
};
