const PRICE_NOTE = `Fiyat; işin tanımı, konumu ve kapsamına göre belirlenir.`;

export default {
  code: 'tr',
  htmlLang: 'tr',
  ogLocale: 'tr_TR',
  label: 'Türkçe',
  short: 'TR',
  priceNote: PRICE_NOTE,

  slugs: {
    regions: 'bolgeler',
    how: 'nasil-calisiyoruz',
    about: 'hakkimizda',
    faq: 'sik-sorulan-sorular',
    contact: 'iletisim',
    privacy: 'gizlilik-ve-kvkk',
  },

  ui: {
    skip: `İçeriğe geç`,
    menu: `Menü`,
    close: `Kapat`,
    langLabel: `Dil`,
    home: `Ana sayfa`,
    services: `Hizmetler`,
    regions: `Bölgeler`,
    allServices: `Tüm hizmetler`,
    allRegions: `Hizmet verdiğimiz bölgeler`,
    inShort: `Kısaca`,
    readMore: `Devamını oku`,
    scope: `Kapsam`,
    approach: `Nasıl çalışıyoruz`,
    faqTitle: `Sık sorulan sorular`,
    relatedServices: `İlgili hizmetler`,
    serviceArea: `Fethiye ve Seydikemer`,
    updated: `Güncelleme`,
    breadcrumb: `Neredesiniz`,

    ctaQuote: `Ücretsiz keşif talebi`,
    ctaQuoteShort: `Teklif al`,
    ctaWhatsapp: `WhatsApp`,
    ctaCall: `Ara`,
    ctaPlan: `Ev Bakım Planı`,
    ctaMore: `Ayrıntılar`,

    formTitle: `Ücretsiz keşif talebi`,
    formIntro: `Formu doldurun, mesai saatleri içinde 2 saat içinde dönüş yapalım. Keşif ücretsizdir.`,
    fName: `Adınız`,
    fPhone: `Telefon / WhatsApp`,
    fEmail: `E-posta (isteğe bağlı)`,
    fService: `Hangi hizmet?`,
    fRegion: `Konum`,
    fMessage: `Kısaca ne yapılması gerekiyor?`,
    fChoose: `Seçiniz`,
    fOther: `Diğer`,
    fConsent: `Kişisel verilerimin talebimi değerlendirmek amacıyla işlenmesini kabul ediyorum.`,
    fConsentLink: `Gizlilik ve KVKK metni`,
    fSubmit: `Talebi gönder`,
    fSending: `Gönderiliyor…`,
    fOk: `Talebiniz bize ulaştı. En kısa sürede sizi arayacağız.`,
    fErr: `Talep gönderilemedi. Lütfen WhatsApp üzerinden yazın veya telefonla arayın.`,
    fRequired: `Bu alan zorunlu.`,
    fPhotoHint: `Fotoğrafınız varsa WhatsApp üzerinden gönderebilirsiniz — keşfi hızlandırır.`,

    trust: [
      `Tek muhatap: usta değil, firma`,
      `Yazılı sözleşme ve işçilik garantisi`,
      `Keşif ücretsiz`,
      `Türkçe · English · Русский`,
      `Fotoğraflı iş raporu`,
    ],

    footerAbout: `Fethiye ve Seydikemer bölgesinde boya ve tadilat, havuz bakımı, bahçe bakımı ve su tesisatı hizmetlerini kurumsal sorumlulukla veren hizmet şirketi.`,
    footerContact: `İletişim`,
    footerLegal: `Yasal`,
    footerHours: `Çalışma saatleri`,
    footerWeekdays: `Pazartesi–Cuma`,
    footerSaturday: `Cumartesi`,
    footerSunday: `Pazar`,
    footerClosed: `Kapalı`,
    rights: `Tüm hakları saklıdır.`,

    notFoundTitle: `Sayfa bulunamadı`,
    notFoundText: `Aradığınız sayfa taşınmış veya kaldırılmış olabilir.`,
    notFoundCta: `Ana sayfaya dön`,
  },

  home: {
    title: `Fethiye ve Seydikemer'de Usta Hizmeti | Ustam Fethiye`,
    description: `Fethiye ve Seydikemer bölgesinde boya-tadilat, havuz bakımı, bahçe bakımı ve su tesisatı. Keşif ücretsiz, yazılı sözleşme, işçilik garantisi. Türkçe, İngilizce, Rusça.`,
    h1: `Ustayı siz aramayın. Sorumluluğu biz alalım.`,
    lede: `Fethiye ve Seydikemer'de boya-tadilat, havuz, bahçe ve su tesisatı. Keşiften teslime her şey tek firmadan.`,

    promiseTitle: `Neden Ustam Fethiye?`,
    promiseLede: `Fethiye'de usta bulmak zor değil; gelen ustanın geleceğinden ve işin bitirileceğinden emin olmak zor. Biz tam olarak bu sorunu çözüyoruz.`,
    promises: [
      { t: `Tek muhatap`, d: `İşi kimin yaptığı değil, kimin arkasında durduğu önemli. Bir sorun çıkarsa muhatabınız firmadır.` },
      { t: `Yazılı sözleşme`, d: `İş kapsamı, süre, kullanılacak malzeme ve garanti tek belgede yazılı olarak tanımlanır.` },
      { t: `Ücretsiz keşif`, d: `Yerinde ölçü alır, fotoğraflar, kapsamı netleştirir ve yazılı teklifi hazırlarız.` },
      { t: `İşçilik garantisi`, d: `Teslim edilen işin arkasında dururuz. Garanti kapsamı sözleşmede yazılıdır.` },
      { t: `Kendi dilinizde`, d: `Türkçe, İngilizce ve Rusça iletişim; teklif ve sözleşme dahil.` },
      { t: `Fotoğraflı iş raporu`, d: `Evinizden uzaktaysanız işin öncesini, ilerleyişini ve sonucunu fotoğrafla görürsünüz.` },
    ],

    servicesTitle: `Hizmetlerimiz`,
    servicesLede: `Dört ana hizmet ve evini uzaktan yönetenler için hazırlanan bakım planı.`,

    howTitle: `Keşiften teslime dört adım`,
    howLede: `Her iş aynı sırayı izler. Sürpriz yok.`,

    regionsTitle: `Hizmet verdiğimiz bölgeler`,
    regionsLede: `Fethiye ve Seydikemer ilçelerinin tamamı. Bölgeye özel notlar için sayfalara göz atın.`,

    planTitle: `Eviniz burada, siz uzakta mısınız?`,
    planLede: `Ev Bakım Planı, yılın büyük bölümünde boş kalan evler için aylık sabit ücretli bakım paketidir. Düzenli kontrol ziyareti, havuz ve bahçe bakımı ve her ay fotoğraflı rapor.`,

    faqTitle: `Merak edilenler`,
    ctaTitle: `Keşif için bize yazın`,
    ctaLede: `Keşif talebi bırakın, WhatsApp'tan yazın ya da arayın. Mesai saatleri içinde 2 saat içinde dönüş yapıyoruz.`,
  },

  services: {
    painting: {
      slug: 'boya-tadilat',
      name: `Boya ve Tadilat`,
      short: `Boya · Tadilat`,
      tagline: `İç ve dış cephe boyası, alçı ve dekorasyon, banyo–mutfak yenileme.`,
      title: `Fethiye Boya ve Tadilat Hizmeti | Ustam Fethiye`,
      description: `Fethiye ve Seydikemer bölgesinde iç–dış cephe boyası, tadilat, banyo ve mutfak yenileme. Ücretsiz keşif, yazılı sözleşme, işçilik garantisi.`,
      summary: [
        `Fethiye ve Seydikemer bölgesinde iç cephe, dış cephe boyası ve ev tadilatı yapıyoruz.`,
        `Keşif ücretsizdir; kapsam, süre ve kullanılacak malzeme yazılı teklifte tanımlanır.`,
        `İşler yazılı sözleşme ile başlar ve işçilik garantisi ile teslim edilir.`,
        PRICE_NOTE,
      ],
      intro: [
        `Boya ve tadilat işlerinde en sık yaşanan sorun, işin ortasında kapsamın değişmesi ve fiyatın kaymasıdır. Bunu keşif aşamasında çözüyoruz: yerinde ölçü alıyor, yüzeyin durumunu fotoğraflıyor, hazırlık işlerini de kapsama dahil ediyoruz. Böylece teklif ettiğimiz iş, teslim ettiğimiz iş oluyor.`,
        `Fethiye'nin iklimi dış cephede belirleyici. Deniz nemi, tuz ve yaz güneşi boyayı hızlı yıpratır; yüzey hazırlığı yapılmadan atılan boya bir sezonda döker. Bu yüzden çatlak onarımı, astar ve nem kontrolü teklifin ayrı kalemleridir — sonradan çıkan sürpriz değil.`,
      ],
      scope: [
        `İç cephe boyası (silinebilir, saten, mat)`,
        `Dış cephe boyası ve cephe yenileme`,
        `Alçı, saten alçı ve yüzey düzeltme`,
        `Çatlak, rutubet ve küf kaynaklı yüzey onarımı`,
        `Banyo ve mutfak yenileme`,
        `Seramik ve fayans uygulaması`,
        `Alçıpan bölme duvar ve asma tavan`,
        `Kapı, pencere ve ahşap doğrama boyası`,
        `Kartonpiyer ve dekoratif detaylar`,
      ],
      approach: [
        `Mobilya, zemin ve doğrama işe başlamadan önce örtülür ve maskelenir.`,
        `Kullanılacak boya markası ve kat sayısı sözleşmede yazılıdır.`,
        `Şantiye her gün toplanır; iş bitiminde ince temizlik yapılır.`,
        `Teslimde birlikte kontrol listesi üzerinden geçilir.`,
      ],
      faq: [
        { q: `Boya işi için keşif şart mı?`, a: `Evet. Metrekare kadar yüzeyin durumu da fiyatı belirler; çatlak, rutubet veya eski boyanın cinsi işin kapsamını değiştirir. Telefonda verilen tahmini fiyatlar sonradan anlaşmazlığa dönüşüyor, bu yüzden keşifsiz fiyat vermiyoruz. Keşif ücretsizdir.` },
        { q: `Boyayı siz mi alıyorsunuz, biz mi?`, a: `İkisi de olabilir. Malzemeyi biz temin edersek marka ve kat sayısı sözleşmede yazılır, garanti işçilik ve uygulamayı birlikte kapsar. Malzemeyi siz temin ederseniz işçilik garantisi devam eder, malzeme kaynaklı sorunlar kapsam dışında kalır.` },
        { q: `Ev boşken yapılabilir mi?`, a: `Evet, en çok tercih edilen yöntem budur. Anahtar teslim alınır, tutanakla kayda geçirilir ve işin her aşaması fotoğraflanarak size iletilir. Yurt dışındaki ev sahiplerinin çoğu bu şekilde çalışıyor.` },
        { q: `İş ne kadar sürer?`, a: `Süre keşifte belirlenir ve sözleşmeye yazılır. Orta ölçekli bir daire içi boya birkaç gün, kapsamlı bir tadilat birkaç hafta sürebilir. Başlangıç ve teslim tarihi teklifte yer alır.` },
        { q: `Dış cephe için hangi mevsim uygun?`, a: `Dış cephe için ilkbahar ve sonbahar en uygun dönem. Yaz ortasında yüksek sıcaklık boyanın kuruma davranışını, kış aylarında nem ve yağış tutunmayı olumsuz etkiler. İç mekân işleri yıl boyu yapılabilir.` },
      ],
    },

    pool: {
      slug: 'havuz-bakimi',
      name: `Havuz Bakımı`,
      short: `Havuz`,
      tagline: `Düzenli bakım, su dengesi, sezon açılış ve kapanış işlemleri.`,
      title: `Fethiye Havuz Bakımı ve Temizliği | Ustam Fethiye`,
      description: `Fethiye ve Seydikemer bölgesinde haftalık havuz bakımı, su dengesi, filtre kontrolü, sezon açılış-kapanış. Aylık bakım anlaşması, düzenli rapor.`,
      summary: [
        `Fethiye ve Seydikemer bölgesinde villa ve site havuzlarına düzenli bakım hizmeti veriyoruz.`,
        `Haftalık, iki haftalık veya aylık ziyaret programı kurulur; her ziyaret kayda geçer.`,
        `Sezon açılışı, kapanışı ve kış bakımı hizmet kapsamındadır.`,
        PRICE_NOTE,
      ],
      intro: [
        `Havuz bakımı, tek seferlik bir iş değil düzenli bir programdır. Su dengesi haftalar içinde bozulur; kimyasal değerler kontrol edilmeyen bir havuzda yeşillenme, kireçlenme ve ekipman aşınması kaçınılmazdır. Bu yüzden havuz bakımını aylık bakım anlaşması olarak kurguluyoruz.`,
        `Evinde sürekli oturmayan ev sahipleri için havuz, en çok kaygı yaratan başlık. Siz burada değilken havuzun ne durumda olduğunu bilmek için her ziyaretten sonra kısa bir not ve fotoğraf gönderiyoruz.`,
      ],
      scope: [
        `Yüzey ve dip temizliği, süpürme ve fırçalama`,
        `Su değerlerinin ölçümü (pH, klor, alkalinite) ve kimyasal dengeleme`,
        `Filtre temizliği ve ters yıkama`,
        `Pompa, motor ve tesisat kontrolü`,
        `Skimmer ve ön filtre sepetlerinin boşaltılması`,
        `Sezon açılışı: su hazırlama, ekipman devreye alma`,
        `Sezon kapanışı ve kış bakımı`,
        `Küçük onarımlar: conta, nozul, aydınlatma armatürü`,
      ],
      approach: [
        `Her ziyaret sonrası ölçülen değerler ve yapılan işlem kayda geçer.`,
        `Kimyasal seviyeleri düşen havuzlarda ürün takviyesi önceden bildirilir.`,
        `Ekipmanda arıza tespit edilirse önce bilgilendirme, sonra onay, sonra işlem.`,
        `Sezon açılışı için mart–nisan döneminde önceden randevu planlanır.`,
      ],
      faq: [
        { q: `Havuz bakımı hangi sıklıkla yapılmalı?`, a: `Yaz aylarında ve havuz aktif kullanılıyorken haftada bir bakım standarttır. Kullanım yoğunsa veya havuz ağaç altındaysa haftada iki ziyaret gerekebilir. Kış aylarında havuz kapatılmışsa iki haftada bir veya aylık kontrol yeterlidir.` },
        { q: `Kimyasalları siz mi getiriyorsunuz?`, a: `Evet, bakım anlaşmasında kimyasal tedariki bize aittir ve kullanılan miktar kayıt altına alınır. Dilerseniz kendi ürünlerinizin kullanılmasını da tercih edebilirsiniz; bu durum anlaşmada belirtilir.` },
        { q: `Ben yurt dışındayken bakım yapılabilir mi?`, a: `Evet. Ev sahiplerinin çoğu bu şekilde çalışıyor. Havuz alanına erişim yöntemi tutanakla kayıt altına alınır ve her ziyaretten sonra fotoğraflı kısa rapor gönderilir. Bu hizmet Ev Bakım Planı kapsamına da dahil edilebilir.` },
        { q: `Havuzum yeşillendi, düzeltebilir misiniz?`, a: `Evet. Yeşillenmiş havuz için önce bir düzeltme (şok) işlemi yapılır, ardından düzenli bakım programına geçilir. Düzeltme işlemi, süresi ve kapsamı bakımdan ayrı olarak keşifte belirlenir.` },
        { q: `Kışın havuza ne yapılıyor?`, a: `Havuz kapanış işlemiyle kışa hazırlanır: su seviyesi ayarlanır, tesisat boşaltılır veya don koruması yapılır, kış kimyasalı verilir ve örtü uygulanır. Kış boyunca periyodik kontrol önerilir; donmuş veya taşmış su ekipmana zarar verebilir.` },
      ],
    },

    garden: {
      slug: 'bahce-bakimi',
      name: `Bahçe Bakımı`,
      short: `Bahçe`,
      tagline: `Çim, budama, sulama sistemi ve mevsimlik bakım.`,
      title: `Fethiye Bahçe Bakımı ve Peyzaj Bakımı | Ustam Fethiye`,
      description: `Fethiye ve Seydikemer bölgesinde düzenli bahçe bakımı: çim biçme, budama, sulama sistemi kontrolü, ağaç bakımı ve mevsimlik dikim.`,
      summary: [
        `Fethiye ve Seydikemer bölgesinde villa ve site bahçelerine düzenli bakım hizmeti veriyoruz.`,
        `Periyodik ziyaret programı kurulur; çim, budama, sulama ve temizlik tek pakette yürütülür.`,
        `Bahçe atıkları her ziyaret sonunda bahçeden kaldırılır.`,
        PRICE_NOTE,
      ],
      intro: [
        `Fethiye ikliminde bahçe yıl boyu bakım ister. Yaz sıcağında sulama sisteminin çalışması, kışın budama ve gübreleme belirleyicidir. Bakımsız kalan bir bahçeyi toparlamak, düzenli bakımdan her zaman daha pahalıdır.`,
        `Bahçe bakımını da havuzda olduğu gibi periyodik program olarak kuruyoruz. Ziyaret sıklığı bahçenin büyüklüğüne, bitki dokusuna ve kullanım şeklinize göre keşifte belirlenir.`,
      ],
      scope: [
        `Çim biçme, kenar düzeltme ve havalandırma`,
        `Çalı, çit ve süs bitkisi budaması`,
        `Zeytin, narenciye ve palmiye bakımı`,
        `Damlama ve fıskiye sulama sistemi kontrolü, tıkanıklık açma`,
        `Gübreleme ve toprak bakımı`,
        `Yabani ot temizliği`,
        `Mevsimlik çiçek ve bitki dikimi`,
        `Bahçe temizliği ve atıkların kaldırılması`,
      ],
      approach: [
        `Ziyaret programı sezon başında planlanır ve size bildirilir.`,
        `Budama zamanlaması bitkinin türüne göre yapılır, takvime göre değil.`,
        `Sulama sistemi her ziyarette kısa kontrolden geçer.`,
        `Kesilen dal ve bahçe atığı bahçede bırakılmaz.`,
      ],
      faq: [
        { q: `Bahçe bakımı ne sıklıkta yapılmalı?`, a: `Çim alanı olan bahçelerde yaz döneminde haftada bir, ilkbahar ve sonbaharda iki haftada bir bakım tipiktir. Ağırlıklı olarak ağaç ve çalıdan oluşan bahçelerde aylık ziyaret yeterli olabilir. Program keşifte birlikte belirlenir.` },
        { q: `Sulama sistemi arızasını da onarıyor musunuz?`, a: `Damlama hattı, fıskiye başlığı, filtre ve zaman ayarlı vana gibi bahçe sulama bileşenlerinin bakımı ve onarımı kapsamdadır. Ana su hattı ve depo tarafındaki işler su tesisatı hizmetimizle birlikte planlanır.` },
        { q: `Budamayı hangi dönemde yapıyorsunuz?`, a: `Bitki türüne göre değişir. Zeytin ve meyve ağaçlarında kış sonu, süs bitkilerinde ve çitlerde büyüme dönemi boyunca periyodik budama yapılır. Yanlış mevsimde yapılan budama bitkiye zarar verir; bu yüzden takvimi bitki belirler.` },
        { q: `Ağaç kesimi yapıyor musunuz?`, a: `Bakım kapsamında budama ve şekillendirme yapıyoruz. Büyük ağaç kesimi izne tabi olabilir ve ayrı ekipman gerektirir; bu tür işleri keşifte ayrıca değerlendiriyoruz.` },
        { q: `Ben burada değilken bahçeye bakılabilir mi?`, a: `Evet. Bahçe bakımı, uzaktaki ev sahipleri için en çok tercih edilen hizmetimiz. Her ziyaretten sonra fotoğraflı kısa rapor gönderiyoruz; hizmet Ev Bakım Planı kapsamına da alınabilir.` },
      ],
    },

    plumbing: {
      slug: 'su-tesisati',
      name: `Su Tesisatı`,
      short: `Tesisat`,
      tagline: `Kaçak tespiti, onarım, armatür değişimi ve tesisat yenileme.`,
      title: `Fethiye Su Tesisatı ve Kaçak Tespiti | Ustam Fethiye`,
      description: `Fethiye ve Seydikemer bölgesinde su tesisatı: kaçak tespiti ve onarım, gider açma, armatür değişimi, hidrofor ve depo, tesisat yenileme.`,
      summary: [
        `Fethiye ve Seydikemer bölgesinde su tesisatı onarım ve yenileme işleri yapıyoruz.`,
        `Kaçak tespiti, gider tıkanıklığı, armatür değişimi ve tesisat yenileme kapsamdadır.`,
        `İşler yazılı sözleşme ile yapılır ve işçilik garantisi verilir.`,
        PRICE_NOTE,
      ],
      intro: [
        `Su kaçağı, evdeki en pahalı hasarın kaynağıdır — özellikle ev boşken fark edilmeyen bir kaçak duvar, zemin ve mobilyayı birlikte götürür. Bu yüzden tesisat işlerinde önce sorunun kaynağını tespit ediyor, sonra onarımı planlıyoruz.`,
        `Fethiye'de sık karşılaşılan iki durum var: kışın boş kalan evlerde don ve durgun su kaynaklı sorunlar, sahil hattında ise su sertliği ve kireçlenmenin armatür ile tesisat ömrünü kısaltması. Her ikisi de düzenli kontrolle önlenebilir.`,
      ],
      scope: [
        `Su kaçağı tespiti ve onarımı`,
        `Gider ve pissu tıkanıklığı açma`,
        `Batarya, armatür ve duş sistemi değişimi`,
        `Klozet, lavabo ve küvet montajı`,
        `Su deposu ve hidrofor kurulumu, bakımı`,
        `Boru hattı yenileme ve tesisat değişimi`,
        `Filtre ve arıtma bağlantıları`,
        `Kışa hazırlık: don koruması ve tesisat boşaltma`,
        `Sezon öncesi su açma ve tesisat kontrolü`,
      ],
      approach: [
        `Önce kaynak tespiti, sonra onarım planı; gereksiz kırım yapılmaz.`,
        `Kırım gereken durumlarda kapsam ve onarım sonrası düzeltme teklifte yazılır.`,
        `Kullanılan malzeme ve markalar kayıt altına alınır.`,
        `İş sonrası su tesisatı basınç ve akış kontrolünden geçirilir.`,
      ],
      faq: [
        { q: `Su kaçağını duvarı kırmadan bulabiliyor musunuz?`, a: `Önce görünür kontrol, sayaç takibi ve basınç testi ile kaçağın bölgesini daraltıyoruz. Amaç kırım alanını en aza indirmek. Kaçağın kesin yeri tespit edilmeden kırım yapılmaz; tespit sonrası kırım gerekiyorsa kapsamı önceden bildiririz.` },
        { q: `Acil durumda ne kadar sürede gelebiliyorsunuz?`, a: `Mesai saatleri içinde gelen taleplere 2 saat içinde dönüş yapıyoruz. Yerinde müdahale zamanı konuma ve o günkü programa göre planlanır; aktif su kaçağı gibi acil durumlarda önceliklendirilir.` },
        { q: `Evim kışın boş kalıyor, ne yapmalıyım?`, a: `Kışa hazırlık işlemi öneriyoruz: ana vananın kapatılması, tesisatın boşaltılması veya don koruması ve dönüş öncesi tesisat kontrolü. Bu işlemler Ev Bakım Planı kapsamına da alınabilir; uzun süre boş kalan evlerde en sık karşılaşılan hasar bu şekilde önleniyor.` },
        { q: `Malzemeyi siz mi getiriyorsunuz?`, a: `Genellikle biz temin ediyoruz; kullanılan ürünler teklifte ve teslim belgesinde yazılı olur. Kendi seçtiğiniz armatür veya ürünleri de uygulayabiliriz — bu durumda işçilik garantisi devam eder, ürün garantisi üreticiye ait olur.` },
        { q: `Tesisat yenilemede ev kullanılamaz hâle gelir mi?`, a: `Kapsamına bağlı. Nokta onarımlarda kesinti birkaç saattir. Bütün tesisatın yenilendiği işlerde su kesintisi ve kırım süresi keşifte belirlenir ve teklifte gün olarak yazılır.` },
      ],
    },

    homecare: {
      slug: 'ev-bakim-plani',
      name: `Ev Bakım Planı`,
      short: `Ev Bakım Planı`,
      tagline: `Uzaktaki ev sahipleri için aylık düzenli kontrol ve bakım.`,
      title: `Ev Bakım Planı — Fethiye ve Seydikemer | Ustam Fethiye`,
      description: `Yılın büyük bölümünde boş kalan evler için aylık bakım planı: düzenli kontrol ziyareti, havuz ve bahçe bakımı, fotoğraflı rapor, sezon hazırlığı.`,
      featured: true,
      summary: [
        `Ev Bakım Planı, yılın büyük bölümünde boş kalan evler için aylık bakım paketidir.`,
        `Kapsam: düzenli kontrol ziyareti, fotoğraflı rapor, havuz ve bahçe bakımı, sezon açılış ve kapanış hazırlığı.`,
        `Plan sahiplerinin tesisat ve tadilat talepleri önceliklendirilir.`,
        PRICE_NOTE,
      ],
      intro: [
        `Fethiye ve Seydikemer'de binlerce ev yılın yalnızca birkaç ayında kullanılıyor. Sahibi uzakta olan bir evde küçük bir su kaçağı aylarca fark edilmez, bahçe kontrolden çıkar, havuz bozulur ve sezon başında karşınıza büyük bir masraf çıkar.`,
        `Ev Bakım Planı bunu önlemek için kurulmuş bir programdır: eve düzenli olarak gidilir, kontrol listesi üzerinden geçilir ve her ziyaretten sonra size fotoğraflı rapor gönderilir. Siz burada değilken evinizin durumunu her ay görürsünüz.`,
      ],
      scope: [
        `Aylık kontrol ziyareti ve kontrol listesi`,
        `Fotoğraflı aylık durum raporu`,
        `Su kaçağı, nem ve rutubet kontrolü`,
        `Havuz bakımı (paket seçimine göre)`,
        `Bahçe bakımı (paket seçimine göre)`,
        `Sezon öncesi açılış hazırlığı: havalandırma, temizlik, su ve tesisat kontrolü`,
        `Sezon sonrası kapanış: kışa hazırlık, don koruması`,
        `Misafir veya kiracı öncesi hazırlık kontrolü`,
        `Tespit edilen sorunlarda ilk müdahale ve bilgilendirme`,
      ],
      approach: [
        `Her ev için sabit bir kontrol listesi oluşturulur; ziyaretler bu listeye göre yapılır.`,
        `Anahtar teslim alınması durumunda teslim ve iade tutanakla kayıt altına alınır.`,
        `Bir sorun tespit edilirse önce bilgilendirme yapılır; onayınız olmadan işlem başlatılmaz.`,
        `Plan kapsamı dışındaki işler ayrı teklifle yürütülür, plan sahiplerine öncelik verilir.`,
      ],
      faq: [
        { q: `Ev Bakım Planı kimler için uygun?`, a: `Fethiye veya Seydikemer'de evi olup yılın büyük bölümünde başka bir şehirde ya da ülkede yaşayan ev sahipleri, kiraya verilen villa sahipleri ve evini sezonluk kullanan aileler için tasarlandı.` },
        { q: `Anahtarı size vermek zorunda mıyım?`, a: `Hayır, zorunlu değil. Anahtarsız da bahçe ve havuz gibi dış alan hizmetleri yürütülebilir. Ev içi kontrol isteniyorsa anahtar teslimi gerekir; teslim ve iade tutanakla kayıt altına alınır.` },
        { q: `Rapor nasıl geliyor?`, a: `Her ziyaretten sonra tarihli fotoğraflar ve kısa bir not WhatsApp veya e-posta ile gönderilir. Bir sorun tespit edilmişse fotoğrafla birlikte açıklaması ve önerimiz iletilir.` },
        { q: `Plan kapsamında olmayan bir iş çıkarsa ne oluyor?`, a: `Önce size bildirilir. Onay verirseniz iş ayrı bir teklif ve sözleşmeyle yürütülür. Plan sahipleri planlama sırasında önceliklendirilir.` },
        { q: `Plan taahhütlü mü?`, a: `Program aylık yürür ve ziyaret sıklığı ile kapsam keşifte birlikte belirlenir. Ayrıntılar sözleşmede yazılı olarak tanımlanır.` },
      ],
    },
  },

  regions: {
    title: `Hizmet Bölgeleri — Fethiye ve Seydikemer | Ustam Fethiye`,
    description: `Fethiye merkez, Çalış, Ölüdeniz, Ovacık, Hisarönü, Kayaköy, Göcek, Üzümlü ve Seydikemer bölgelerinde boya-tadilat, havuz, bahçe ve su tesisatı hizmeti.`,
    h1: `Hizmet verdiğimiz bölgeler`,
    lede: `Fethiye ve Seydikemer ilçelerinin tamamına hizmet veriyoruz. Her bölgenin kendine özgü koşulları var; aşağıdaki sayfalarda o bölgede en çok karşılaştığımız işleri anlattık.`,
    inRegion: `Bu bölgede en çok yaptığımız işler`,
    regionNotes: `Bölgeye özel notlar`,
    items: {
      'merkez': {
        slug: 'fethiye-merkez',
        name: `Fethiye Merkez`,
        intro: `Fethiye merkezde apartman daireleri, site içi konutlar ve iş yerleri ağırlıkta. En sık gelen talepler iç mekân boya-tadilat, banyo–mutfak yenileme ve tesisat onarımı.`,
        notes: [
          `Apartman ve sitelerde çalışma saatleri ve gürültü kuralları var; iş programını yönetimle uyumlu planlıyoruz.`,
          `Merkezdeki eski yapılarda tesisat borularının yaşı sık sorun kaynağı; nokta onarım yerine hat yenileme daha ekonomik olabiliyor.`,
          `Asansörsüz binalarda malzeme taşıma iş süresini etkiliyor; bunu keşifte hesaba katıyoruz.`,
        ],
        services: ['painting', 'plumbing', 'homecare'],
      },
      'calis': {
        slug: 'calis',
        name: `Çalış`,
        intro: `Çalış sahil hattına yakın konutlarda tuzlu nem ve rüzgâr belirleyici. Dış cephe boyası, doğrama bakımı ve tesisat kireçlenmesi bu bölgede öne çıkıyor.`,
        notes: [
          `Denize yakın cephelerde tuz ve nem boyayı hızlandırılmış şekilde yıpratıyor; yüzey hazırlığı ve doğru astar burada kritik.`,
          `Metal korkuluk, doğrama ve dış mekân aksamında korozyon kontrolü düzenli bakım gerektiriyor.`,
          `Kış aylarında rüzgâr ve yağış nedeniyle dış cephe işleri için mevsim planlaması yapıyoruz.`,
        ],
        services: ['painting', 'garden', 'homecare'],
      },
      'oludeniz': {
        slug: 'oludeniz',
        name: `Ölüdeniz`,
        intro: `Ölüdeniz'de havuzlu villa ve kiralık konut yoğunluğu yüksek. Sezon boyunca yoğun kullanılan havuzlar ve misafir dönüşümü olan evler düzenli bakım istiyor.`,
        notes: [
          `Kiralanan villalarda havuz kullanımı yoğun olduğu için haftalık bakım genellikle yeterli olmuyor; program buna göre kuruluyor.`,
          `Misafir giriş-çıkış dönemlerinde hızlı kontrol ve küçük onarım talepleri sık; bunlar için önceden takvim planlıyoruz.`,
          `Sezon açılışı öncesi mart–nisan döneminde havuz ve tesisat kontrolü talebi yoğunlaşıyor, randevuyu erken almanızı öneriyoruz.`,
        ],
        services: ['pool', 'garden', 'homecare'],
      },
      'ovacik-hisaronu': {
        slug: 'ovacik-hisaronu',
        name: `Ovacık ve Hisarönü`,
        intro: `Ovacık ve Hisarönü'nde yabancı ev sahibi oranı yüksek ve konutların önemli bölümü yılın büyük kısmında boş kalıyor. Uzaktan takip edilebilen düzenli bakım burada en çok ihtiyaç duyulan hizmet.`,
        notes: [
          `Uzun süre kapalı kalan evlerde nem, rutubet ve durgun su kaynaklı tesisat sorunları en sık karşılaştığımız durum.`,
          `Ev sahiplerinin çoğu yurt dışında; iletişimi İngilizce veya Rusça yürütüyor, her ziyarette fotoğraflı rapor gönderiyoruz.`,
          `Site içi konutlarda ortak alan kuralları ve yönetim izinleri iş planını etkiliyor; bunu önceden çözüyoruz.`,
        ],
        services: ['homecare', 'plumbing', 'pool'],
      },
      'kayakoy': {
        slug: 'kayakoy',
        name: `Kayaköy`,
        intro: `Kayaköy ve çevresinde taş yapı ve eski doku ağırlıkta. Bu yapılarda boya ve onarım işleri, standart konutlardan farklı bir yaklaşım gerektiriyor.`,
        notes: [
          `Taş ve eski sıva yüzeylerde nefes alan ürün seçimi önemli; yanlış kaplama rutubeti duvarın içinde hapsediyor.`,
          `Rutubet ve küf kaynaklı yüzey sorunları için önce nem kaynağının çözülmesi, sonra boya yapılması gerekiyor.`,
          `Bahçe ve zeytinlik bakımı bölgede sık talep edilen hizmet; budama takvimi ağaca göre planlanıyor.`,
        ],
        services: ['painting', 'garden', 'homecare'],
      },
      'gocek': {
        slug: 'gocek',
        name: `Göcek`,
        intro: `Göcek'te villa ve site standartları yüksek, beklenti düzenli ve kesintisiz bakım yönünde. Havuz, bahçe ve ev bakımı çoğunlukla sözleşmeli olarak yürütülüyor.`,
        notes: [
          `Site yönetimleri ve villa sahipleri için düzenli program ve raporlama esas; her ziyaret kayda geçiyor.`,
          `Sezon boyunca evin kullanıma hazır tutulması bekleniyor; kontrol ziyaretleri buna göre sıklaştırılıyor.`,
          `Göcek merkeze uzaklık nedeniyle ziyaret programını verimli planlıyor, plansız gidiş-gelişi en aza indiriyoruz.`,
        ],
        services: ['pool', 'garden', 'homecare'],
      },
      'uzumlu': {
        slug: 'uzumlu',
        name: `Üzümlü`,
        intro: `Üzümlü sahilden yüksekte ve kışları belirgin şekilde daha soğuk. Bu nedenle kışa hazırlık ve don koruması bölgede öne çıkan iş kalemleri.`,
        notes: [
          `Kış aylarında boş kalan evlerde tesisat donması gerçek bir risk; sezon kapanışında boşaltma ve don koruması öneriyoruz.`,
          `Rakım farkı nedeniyle bahçe bakım takvimi sahil hattından farklı ilerliyor; budama ve dikim zamanlaması buna göre yapılıyor.`,
          `Dış cephe işleri için ilkbahar ve sonbahar penceresi sahile göre daha dar; planlamayı erken yapıyoruz.`,
        ],
        services: ['plumbing', 'garden', 'painting'],
      },
      'seydikemer': {
        slug: 'seydikemer',
        name: `Seydikemer`,
        intro: `Seydikemer geniş ve kırsal bir alan; müstakil evler, bahçeli konutlar ve tarım alanları ağırlıkta. Bahçe bakımı, tesisat ve depo–hidrofor işleri en sık gelen talepler.`,
        notes: [
          `Mesafeler uzun olduğu için ziyaretleri gruplayarak planlıyor, ulaşımı iş programına dahil ediyoruz.`,
          `Şebeke basıncının değişken olduğu noktalarda su deposu ve hidrofor kurulumu sık ihtiyaç duyulan çözüm.`,
          `Geniş bahçelerde düzenli bakım programı, tek seferlik toparlama işinden her zaman daha ekonomik oluyor.`,
        ],
        services: ['garden', 'plumbing', 'painting'],
      },
    },
  },

  pages: {
    how: {
      title: `Nasıl Çalışıyoruz — Talepten Teslime | Ustam Fethiye`,
      description: `Ustam Fethiye iş akışı: talep, keşif, yazılı teklif, sözleşme, planlama, uygulama, teslim ve garanti. Her iş aynı sekiz adımdan geçer.`,
      h1: `Nasıl çalışıyoruz`,
      lede: `Her iş aynı sekiz adımdan geçer. Amaç basit: ne yapılacağını, ne kadar süreceğini ve ne kadar tutacağını işe başlamadan önce yazılı olarak bilmeniz.`,
      steps: [
        { t: `Talep`, d: `Form, WhatsApp veya telefonla bize ulaşırsınız. Her talep kayda alınır; mesai saatleri içinde 2 saat içinde dönüş yaparız.` },
        { t: `Ön görüşme`, d: `Kısa bir görüşmeyle işin kapsamını, konumu ve aciliyetini netleştiririz. Varsa fotoğraf göndermeniz süreci hızlandırır.` },
        { t: `Ücretsiz keşif`, d: `Yerinde ölçü alır, fotoğraflar ve notlarız. Keşif Fethiye ve Seydikemer bölgesinde ücretsizdir.` },
        { t: `Yazılı teklif`, d: `Kapsam kalem kalem, süre ve kullanılacak malzeme yazılı olarak iletilir. Teklifin bir geçerlilik süresi vardır.` },
        { t: `Sözleşme`, d: `Kapsam, başlangıç ve teslim tarihi, malzeme ve garanti tek belgede tanımlanır. Sözleşme kendi dilinizde de sunulur.` },
        { t: `Planlama`, d: `Ekip ataması yapılır, malzeme temin edilir ve size başlangıç tarihi bildirilir.` },
        { t: `Uygulama ve denetim`, d: `İş süresince saha kontrolü yapar, ilerlemeyi fotoğrafla kayıt altına alır ve size bildiririz.` },
        { t: `Teslim ve garanti`, d: `Kontrol listesi üzerinden birlikte geçer, iş dosyasını ve garanti belgesini teslim ederiz. Sonrasında memnuniyet araması yaparız.` },
      ],
      guaranteeTitle: `Taahhütlerimiz`,
      guarantees: [
        { t: `Muhatabınız firmadır`, d: `İşi yapan ekip bizim tedarikçimizdir. Sizinle sözleşmesi olan ve işten sorumlu olan taraf Ustam Fethiye'dir.` },
        { t: `Kapsam değişmedikçe fiyat değişmez`, d: `Teklif kabul edildikten sonra, siz talep etmedikçe veya keşifte görülemeyen bir durum çıkmadıkça fiyat sabittir. Böyle bir durumda önce bilgilendirme, sonra onay, sonra işlem.` },
        { t: `İşçilik garantisi`, d: `Teslim ettiğimiz işin arkasında dururuz. Garanti süresi ve kapsamı hizmete göre sözleşmede yazılıdır.` },
        { t: `Ekip ve şantiye düzeni`, d: `Çalışma alanı her gün toparlanır, iş bitiminde ince temizlik yapılır ve atıklar kaldırılır.` },
      ],
    },

    about: {
      title: `Hakkımızda — Ustam Fethiye`,
      description: `Ustam Fethiye, Fethiye ve Seydikemer bölgesinde boya-tadilat, havuz bakımı, bahçe bakımı ve su tesisatı hizmetlerini kurumsal sorumlulukla veren bir hizmet şirketidir.`,
      h1: `Hakkımızda`,
      lede: `Ustam Fethiye, usta bulma sorununu bir aracılık işi olarak değil, sorumluluğu üstlenen bir hizmet şirketi olarak çözmek üzere kuruldu.`,
      body: [
        { t: `Ne yapıyoruz`, p: [
          `Fethiye ve Seydikemer bölgesinde boya ve tadilat, havuz bakımı, bahçe bakımı ve su tesisatı hizmetleri veriyoruz. Keşfi biz yapıyor, teklifi biz hazırlıyor, sözleşmeyi biz imzalıyor, işi planlıyor, denetliyor ve teslim ediyoruz.`,
          `İşi sahada yürüten usta ve ekipler bizim tedarikçimizdir. Sizinle sözleşmesi olan taraf ve işin sonucundan sorumlu olan taraf firmadır. Bu, bizim en temel farkımız.`,
        ]},
        { t: `Neden böyle bir şirket gerekliydi`, p: [
          `Fethiye'de usta bulmak zor değil. Zor olan; gelen ustanın söz verdiği gün geleceğinden, fiyatın işin ortasında değişmeyeceğinden ve işin bitirileceğinden emin olmak. Bir sorun çıktığında arayacak bir muhatabın olması.`,
          `Evi Fethiye'de olup başka bir ülkede yaşayan ev sahipleri için buna bir de dil ve mesafe ekleniyor. Evde ne olup bittiğini görememek, en sık duyduğumuz şikâyet. Bu yüzden her işte fotoğraflı rapor gönderiyoruz.`,
        ]},
        { t: `Nasıl çalışıyoruz`, p: [
          `Her iş yazılı teklif ve sözleşmeyle başlar. Kapsam, süre, kullanılacak malzeme ve garanti işe başlamadan önce yazılıdır. Keşif ücretsizdir ve keşif yapılmadan fiyat vermeyiz — telefonda verilen tahmini rakamlar, sonradan yaşanan anlaşmazlıkların birinci sebebi.`,
          `İletişim tek kanaldan yürür. Sahadaki ekiple siz değil, biz konuşuruz. Sizin muhatabınız her zaman aynı kişidir.`,
        ]},
        { t: `Diller`, p: [
          `Türkçe, İngilizce ve Rusça hizmet veriyoruz. Teklif ve sözleşme dahil olmak üzere tüm yazışmayı tercih ettiğiniz dilde yürütebiliriz.`,
        ]},
      ],
      factsTitle: `Kısa bilgi`,
      facts: [
        { k: `Hizmet bölgesi`, v: `Fethiye ve Seydikemer ilçeleri` },
        { k: `Hizmetler`, v: `Boya ve tadilat, havuz bakımı, bahçe bakımı, su tesisatı, Ev Bakım Planı` },
        { k: `Diller`, v: `Türkçe, İngilizce, Rusça` },
        { k: `Keşif`, v: `Hizmet bölgesi içinde ücretsiz` },
        { k: `Fiyatlandırma`, v: PRICE_NOTE },
        { k: `Sözleşme`, v: `Her iş yazılı sözleşme ile yapılır` },
        { k: `Garanti`, v: `İşçilik garantisi, kapsamı sözleşmede yazılı` },
        { k: `Yanıt süresi`, v: `Mesai saatleri içinde 2 saat` },
      ],
    },

    faq: {
      title: `Sık Sorulan Sorular | Ustam Fethiye`,
      description: `Ustam Fethiye hakkında sık sorulan sorular: keşif, fiyatlandırma, sözleşme, garanti, çalışma bölgesi, diller ve uzaktan takip.`,
      h1: `Sık sorulan sorular`,
      lede: `Aradığınız cevabı bulamazsanız yazın; aynı gün dönüş yapıyoruz.`,
      items: [
        { q: `Hangi bölgelerde hizmet veriyorsunuz?`, a: `Fethiye ve Seydikemer ilçelerinin tamamında hizmet veriyoruz. Fethiye merkez, Çalış, Karagözler, Ölüdeniz, Ovacık, Hisarönü, Kayaköy, Göcek, Üzümlü ve Seydikemer çevresi hizmet bölgemizdedir.` },
        { q: `Keşif ücretli mi?`, a: `Hayır. Fethiye ve Seydikemer hizmet bölgesi içinde keşif ücretsizdir. Keşifte yerinde ölçü alır, fotoğraflar ve ardından yazılı teklifinizi hazırlarız.` },
        { q: `Fiyatı nasıl belirliyorsunuz?`, a: `Fiyat; işin tanımı, konumu ve kapsamına göre belirlenir. Bu nedenle keşif yapılmadan fiyat vermiyoruz. Keşif sonrası hazırlanan teklif kalem kalem yazılıdır ve kapsam değişmedikçe geçerlidir.` },
        { q: `Telefonda yaklaşık bir fiyat söyleyemez misiniz?`, a: `Söyleyebiliriz ama söylemiyoruz. Yerinde görülmeden verilen tahmini rakamlar işin ortasında değişiyor ve bu, bu sektördeki anlaşmazlıkların birinci sebebi. Onun yerine ücretsiz keşif yapıp yazılı ve sabit bir fiyat veriyoruz.` },
        { q: `İşi kim yapıyor?`, a: `İşi, çalıştığımız usta ve ekipler yapar. Ancak sizinle sözleşmesi olan, işi planlayan, denetleyen ve sonucundan sorumlu olan taraf firmadır. Sahadaki ekiple siz değil, biz muhatap oluruz.` },
        { q: `Sözleşme yapıyor musunuz?`, a: `Evet, her iş yazılı sözleşme ile yapılır. Sözleşmede iş kapsamı, başlangıç ve teslim tarihi, kullanılacak malzeme, ödeme koşulları ve garanti yer alır. Sözleşmeyi tercih ettiğiniz dilde de sunuyoruz.` },
        { q: `Garanti veriyor musunuz?`, a: `Evet. Teslim ettiğimiz işlerde işçilik garantisi veriyoruz; süresi ve kapsamı hizmete göre değişir ve sözleşmede yazılı olarak tanımlanır. Malzemeyi biz temin ettiysek ürün garantisi de kapsamda değerlendirilir.` },
        { q: `Yurt dışındayım, evimle nasıl ilgileneceksiniz?`, a: `Ev sahiplerimizin önemli bölümü yurt dışında yaşıyor. İletişimi İngilizce veya Rusça yürütüyor, anahtar teslim alınması gerekiyorsa tutanakla kayıt altına alıyor ve her ziyaret ya da iş aşamasında fotoğraflı rapor gönderiyoruz. Düzenli takip için Ev Bakım Planı hizmetimiz var.` },
        { q: `Hangi dillerde hizmet veriyorsunuz?`, a: `Türkçe, İngilizce ve Rusça. Teklif ve sözleşme dahil olmak üzere tüm yazışma tercih ettiğiniz dilde yürütülebilir.` },
        { q: `Ne kadar sürede dönüş yapıyorsunuz?`, a: `Mesai saatleri içinde gelen taleplere 2 saat içinde dönüyoruz. Mesai dışında gelen talepler ertesi iş günü sabah ilk iş olarak değerlendirilir.` },
        { q: `Malzemeyi kim temin ediyor?`, a: `Genellikle biz temin ediyoruz; kullanılan marka ve ürünler teklifte yazılı olur. Dilerseniz malzemeyi kendiniz de temin edebilirsiniz. Bu durumda işçilik garantimiz devam eder, malzeme kaynaklı sorunlar kapsam dışında kalır.` },
        { q: `Site veya apartman yönetimleriyle çalışıyor musunuz?`, a: `Evet. Site ve apartman yönetimleri, villa kiralama şirketleri ve otel–pansiyon işletmeleri için periyodik bakım ve dönemsel yenileme işleri yapıyoruz. Bu tür işler için ayrı bir görüşme planlıyoruz.` },
      ],
    },

    contact: {
      title: `İletişim ve Ücretsiz Keşif Talebi | Ustam Fethiye`,
      description: `Fethiye ve Seydikemer bölgesinde ücretsiz keşif talebi. Form, WhatsApp veya telefonla ulaşın; mesai saatleri içinde 2 saat içinde dönüş yapıyoruz.`,
      h1: `İletişim`,
      lede: `Keşif ücretsiz. Formu doldurun, WhatsApp'tan yazın ya da doğrudan arayın — mesai saatleri içinde 2 saat içinde dönüş yapıyoruz.`,
      infoTitle: `Doğrudan ulaşın`,
      areaTitle: `Hizmet bölgesi`,
      areaText: `Fethiye ve Seydikemer ilçelerinin tamamı. Merkez, Çalış, Karagözler, Ölüdeniz, Ovacık, Hisarönü, Kayaköy, Göcek, Üzümlü ve çevresi.`,
    },

    privacy: {
      title: `Gizlilik ve KVKK Aydınlatma Metni | Ustam Fethiye`,
      description: `Ustam Fethiye kişisel verilerin işlenmesi, saklanması ve haklarınız hakkında aydınlatma metni.`,
      h1: `Gizlilik ve kişisel verilerin korunması`,
      lede: `Bu metin, iletişim formu ve diğer kanallar aracılığıyla paylaştığınız kişisel verilerin nasıl işlendiğini açıklar.`,
      sections: [
        { t: `Hangi verileri topluyoruz`, p: [`İletişim formu üzerinden adınız, telefon numaranız, isteğe bağlı olarak e-posta adresiniz, talep ettiğiniz hizmet, konumunuz ve mesajınızda paylaştığınız bilgiler toplanır. Ayrıca teknik olarak talebin geldiği sayfa ve tarih kaydedilir.`] },
        { t: `Neden topluyoruz`, p: [`Verileriniz yalnızca talebinizi değerlendirmek, sizinle iletişime geçmek, keşif planlamak, teklif ve sözleşme hazırlamak ve hizmeti yürütmek amacıyla işlenir. Onayınız olmadan pazarlama amaçlı iletişim yapılmaz.`] },
        { t: `Kimlerle paylaşıyoruz`, p: [`Verileriniz üçüncü taraflara satılmaz veya pazarlama amacıyla paylaşılmaz. İşin yürütülmesi için gereken asgari bilgi (örneğin adres ve iş tanımı) yalnızca ilgili ekiple paylaşılır. Yasal yükümlülük halinde yetkili kurumlarla paylaşım yapılabilir.`] },
        { t: `Ne kadar süre saklıyoruz`, p: [`Sonuçlanmayan talepler makul bir süre sonunda silinir. Sözleşmeye dönüşen işlerde veriler, yasal saklama süreleri boyunca muhafaza edilir.`] },
        { t: `Haklarınız`, p: [`6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili mevzuat kapsamında; verilerinize erişme, düzeltilmesini, silinmesini veya işlenmesinin sınırlandırılmasını isteme hakkına sahipsiniz. Avrupa Birliği'nde ikamet ediyorsanız GDPR kapsamındaki haklarınız da geçerlidir. Taleplerinizi aşağıdaki iletişim adresine iletebilirsiniz.`] },
        { t: `Çerezler ve ölçümleme`, p: [`Sitede kişisel veri toplayan reklam veya takip çerezi kullanılmaz. Ziyaret istatistikleri için çerez kullanmayan, kişisel veri toplamayan bir ölçümleme yöntemi tercih edilmiştir.`] },
      ],
    },
  },
};
